### PR TITLE
Graphically nicer dashboard

### PR DESCRIPTION
**Pull request by NicoRicardi**
This dashboard is a good starting point. 
Some tools are ready (see code) but the data is of very poor quality, so they are not displayed (for instance, hospitalisations).

### CODE REVIEW

**Review by eduardocorrearaujo — COMMENTED** [review]
I think it would be great to slice the functions.py file into two other files,  one with the functions used to load the data and preprocess it and the other with the functions used to make the plots.

**Comment by eduardocorrearaujo** [comment]
Captura de Tela 2022-09-13 às 08 00 41
When the `cumulative` option is selected in the checkbox, the name in the plot legend is not updated.

**Comment by eduardocorrearaujo** [comment]
I think the content of the `Additional Information` box in the sidebar should always be shown without the need to click.

**Comment by NicoRicardi** [comment]
> I think it would be great to slice the functions.py file into two other files, one with the functions used to load the data and preprocess it and the other with the functions used to make the plots.

We have, so far, very few processing functions. The almost totality of the functions in the functions file are plotting functions.
Yet, if you confirm, I can do it, it is very quick.

**Comment by fccoelho** [comment]
The Dashboard is runing into a ValueError:
```python
ValueError: Usecols do not match columns, columns expected but not found: ['Country', 'Status', 'Country_ISO3']
```
The code assumes that the `latest.csv` file contains the above columns but it apparently no longer does:
```python
 In [2]: df = pd.read_csv('https://raw.githubusercontent.com/globaldothealth/monkeypox/main/latest.csv')

In [3]: df.columns
Out[3]: 
Index(['_id', 'Pathogen', 'ID', 'Case_status', 'Pathogen_status',
       'Location_information', 'Age', 'Sex_at_birth', 'Sex_at_birth_other',
       'Gender', 'Gender_other', 'Race', 'Race_other', 'Ethnicity',
       'Ethnicity_other', 'Nationality', 'Nationality_other', 'Occupation',
       'Healthcare_worker', 'Previous_infection', 'Co_infection',
       'Pre_existing_condition', 'Pregnancy_Status', 'Vaccination',
       'Vaccine_name', 'Vaccination_date', 'Vaccine_side_effects', 'Symptoms',
       'Date_onset', 'Date_confirmation', 'Confirmation_method',
       'Date_of_first_consultation', 'Hospitalized',
       'Reason_for_hospitalization', 'Date_hospitalization',
       'Date_discharge_hospital', 'Intensive_care', 'Date_admission_ICU',
       'Date_discharge_ICU', 'Home_monitoring', 'Isolated', 'Date_isolation',
       'Outcome', 'Date_death', 'Date_recovered', 'Contact_with_case',
       'Contact_ID', 'Contact_setting', 'Contact_setting_other',
       'Contact_animal', 'Contact_comment', 'Transmission', 'Travel_history',
       'Travel_history_entry', 'Travel_history_start',
       'Travel_history_location', 'Genomics_Metadata', 'Accession_Number',
       'Source', 'Source_II', 'Source_III', 'Source_IV', 'Date_entry',
       'Date_last_modified'],
```
We should look at the data instead of assuming its schema will never change, @NicoRicardi .

**Comment by NicoRicardi** [comment]
Definitely. The issue of the change of csv file was addressed in pull request #5.
In #4, I was using my local version of the file, which is indeed not advisable.

**Pull request merged**
