### PR TITLE
Aggregation to parquet files

### PR DESCRIPTION
**Pull request by NicoRicardi**
Working version with aggregation of cases

### CODE REVIEW

**Comment by fccoelho** [comment]
I had to do a `poetry add scipy` so that it would run.

and that required a small change in pyproject.toml.
Please do that on your end, @NicoRicardi, and make a new commit

**Comment by fccoelho** [comment]
I am getting the following excaeption when loading the dashboard:
```python
2022-10-11 08:56:25.504 Uncaught app exception
Traceback (most recent call last):
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/streamlit/runtime/legacy_caching/caching.py", line 584, in get_or_create_cached_value
    return_value = _read_from_cache(
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/streamlit/runtime/legacy_caching/caching.py", line 345, in _read_from_cache
    raise e
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/streamlit/runtime/legacy_caching/caching.py", line 330, in _read_from_cache
    return _read_from_mem_cache(
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/streamlit/runtime/legacy_caching/caching.py", line 248, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/home/fccoelho/Documentos/Software_projects/MPX-dashboard/app.py", line 34, in <module>
    total_weekly_metrics(all_cases, entrytype='cases', index_col='Date_confirmation')
  File "/home/fccoelho/Documentos/Software_projects/MPX-dashboard/functions.py", line 107, in total_weekly_metrics
    daily_count = get_daily_count(df, index_col=index_col, count_col=count_col)
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/streamlit/runtime/legacy_caching/caching.py", line 618, in wrapped_func
    return get_or_create_cached_value()
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/streamlit/runtime/legacy_caching/caching.py", line 602, in get_or_create_cached_value
    return_value = non_optional_func(*args, **kwargs)
  File "/home/fccoelho/Documentos/Software_projects/MPX-dashboard/functions.py", line 64, in get_daily_count
    return df.set_index(index_col)[count_col].resample('D').count()
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 5875, in resample
    return super().resample(
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/generic.py", line 8863, in resample
    return get_resampler(
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 1518, in get_resampler
    return tg._get_resampler(obj, kind=kind)
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 1687, in _get_resampler
    return DatetimeIndexResampler(
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 167, in __init__
    self.binner, self.grouper = self._get_binner()
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 254, in _get_binner
    binner, bins, binlabels = self._get_binner_for_time()
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 1243, in _get_binner_for_time
    return self.groupby._get_time_bins(self.ax)
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 1721, in _get_time_bins
    first, last = _get_timestamp_range_edges(
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 2003, in _get_timestamp_range_edges
    first, last = _adjust_dates_anchored(
  File "/home/fccoelho/.cache/pypoetry/virtualenvs/streamlit-docker-template-snSCA4V7-py3.10/lib/python3.10/site-packages/pandas/core/resample.py", line 2112, in _adjust_dates_anchored
    origin_nanos = first.normalize().value
AttributeError: 'NaTType' object has no attribute 'normalize'
```

**Comment by fccoelho** [comment]
Thanks @NicoRicardi now the Dashboard runs. Please consider replacing the color scale in the map by a nonlinear one to improve visibility, See [map_classify](https://pysal.org/notebooks/viz/mapclassify/intro.html) library to generate those. I particularly like the Natural Breaks scale for data with this type of distribution.

**Review by fccoelho — CHANGES_REQUESTED** [review]
Please add epigraphub to the project dependencies with a 
```bash
poetry add epigraphhub
```
command.

**Comment by eduardocorrearaujo** [comment]
Hi, @NicoRicardi. What needs to be done to close this PR and merge it in the main?

**Comment by NicoRicardi** [comment]
I am not super sure. I think Ivan took care of MinIo for the MPX and population data. I fear that the population data might be a double with some other file in EGH.
I can remove gitignore if necessary, I was just ignoring local debugging/testing files

**Pull request merged**
